### ISSUE TITLE
Errors when attempting to benchmark

### ISSUE THREAD

**Issue by axelf4** [jojojames/fussy#28]
Heyo!

First off, I tried to write a benchmark for fuzzy Emacs completions styles at [axelf4/emacs-completion-bench](https://github.com/axelf4/emacs-completion-bench). It would be great if you could take a look and see whether there are any glaring mistakes in how the fussy performance is measured.

Second, I run into panics with two of the backends on the benchmark instances. With flx-rs:

    thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flx-rs-0.1.4/src/search.rs:72:53

and with sublime_fuzzy:

    thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/dynmod.rs:15:46

Should be enough to uncomment those [here](https://github.com/axelf4/emacs-completion-bench/blob/d856d126601213777555c69a53de38944270dfbb/bench.el#L61-L65) and running the benchmark in order to reproduce.

**Comment by jojojames** [comment]
How are you running the benchmark? (commands/etc?)

**Comment by axelf4** [comment]
Yes, compile `hotfuzz-module.so` and put it in the directory and then run `./runbench` (which just launces Emacs with some arguments). There are some instructions in the README.

**Comment by jojojames** [comment]
Haven't had much time to look into this (with 2022 closing in), not timelines but the benchmark looks pretty extensive to me.

> Unlike with other dynamic modules that are consulted for each individual each candidate to compute its score, the Hotfuzz Lisp code only calls out to the native code once, passing along the entire completions list. This reduces overhead and enables multithreaded filtering and scoring.

This was something I wanted to do for fussy too but haven't had the time. I think it's definitely the right approach though, if it's possible to work with fussy/emacs' completion system.

**Comment by jojojames** [comment]
Found some time and implemented your threading changes to fzf-native (https://github.com/dangduc/fzf-native/pull/20), it should be decently faster now (likely still slower than hotfuzz but comparable). I didn't look into how to set up the benchmarking for the new function though.

Thanks for heads up and the threading/native module implementation on hotfuzz.

**Comment by jojojames** [comment]
Couple years but I updated the bench and finally ran it.

https://github.com/jojojames/emacs-completion-bench/commit/b3b2f051d3ab4713a04f328a68078e18fc2d0623

Benchmarking on list of 95653 possible completions
	with median length 37.
style basic: (0.062098 0 0.0)
style substring: (0.671968 0 0.0)
style hotfuzz: (0.1267 0 0.0)
style flex: (2.309051 0 0.0)
style (fussy . flx-score): (1.218817 2 0.159856)
style (fussy . flx-rs-score): (3.780919 0 0.0)
style (fussy . fussy-fzf-native-score): (0.59033 0 0.0)
style (fussy . fussy-fuz-bin-score): (0.49091 0 0.0)
style (fussy . fussy-hotfuzz-score): (10.613306 0 0.0)
style (fussy fussy-fzf-score . fussy-filter-by-scoring): (0.339574 0 0.0)
style (fussy fussy-fzf-score . fussy-filter-default): (0.246011 0 0.0)
style orderless: (0.306551 0 0.0)

**Comment by jojojames** [comment]
And to close the loop further:

https://github.com/jojojames/emacs-completion-bench

Benchmarking on list of 95653 possible completions
	with median length 37.
style basic (sort-fn: off): (0.054028 0 0.0)
style (fussy fussy-fzf-score . fussy-filter-default) (sort-fn: off): (0.089606 0 0.0)
style (fussy fussy-fzf-score . fussy-filter-by-scoring) (sort-fn: off): (0.099392 0 0.0)
style hotfuzz (sort-fn: off): (0.114468 0 0.0)
style orderless (sort-fn: off): (0.306948 0 0.0)
style (fussy . fussy-fuz-bin-score) (sort-fn: on): (0.479826 0 0.0)
style substring (sort-fn: off): (0.782333 0 0.0)
style (orderless . flex) (sort-fn: off): (0.841109 0 0.0)
style (fussy . flx-score) (sort-fn: on): (0.977163 2 0.130905)
style flex (sort-fn: off): (2.189211 0 0.0)
style (fussy . flx-rs-score) (sort-fn: on): (4.085732 0 0.0)
