### ISSUE TITLE
fussy with fido-mode

### ISSUE THREAD

**Issue by KaranAhlawat** [jojojames/fussy#30]
First, thanks for creating this package. It's really great to use so far.

Now, following the README, I setup the advice for fido mode to set the completion styles. However, seeing this [issue](https://github.com/oantolin/orderless/issues/110#issuecomment-1088705350) on the Orderless github, I am uncertain whether I still need to add a hook to set the styles after setting up the advice, or if setting the advice is enough.

Any help is appreciated.

**Comment by jojojames** [comment]
I think setting the advice is good enough but it's been a while. You can report back if you're seeing issues.
