### ISSUE TITLE
Integrate with hippe-expand possible?

### ISSUE THREAD

**Issue by tuhdo** [jojojames/fussy#33]
For example, when I type `ffap` and run `hippe-expand`, it turns into `find-file-at-point`?

**Comment by jojojames** [comment]
Seems interesting, would need to do more research there.

**Comment by jojojames** [comment]
It looks like we just need to implement a function and plug it in here: https://github.com/emacs-mirror/emacs/blob/0df28dc00edd0db343619d02aa41999a7bfce5fb/lisp/hippie-exp.el#L204 

Think we could definitely do something like get the symbol at point, get the list of possible completions, score it, and then return the highest scored word in the function. Haven't used hippie expand in a long time but happy to take a PR that adds that function so hippie expand can use it.
