### ISSUE TITLE
Orderless is not, in fact, orderless

### ISSUE THREAD

**Issue by kim366** [jojojames/fussy#41]
Hi, thanks for this package! I have been using it for a while and have found the completion to be quite intuitive, except for a specific case:

The `fzf-native` scorer allows reordering of words, just like `orderless` does. So we can match the command in M-x `"org-goto"` by typing `"goto org"`.

fussy disallows this by feeding the scorer the query `"gotoorg"` instead of `"goto org"`. This, of course does not match, and the candidate is discarded:

https://github.com/jojojames/fussy/blob/4080b373f3361126d4de1f063bb08718b0c08eed/fussy.el#L616-L618

I have "fixed" the issue on my end with a very ugly advice hack:

```elisp
(defun my/allow-reordering-advice-replace-regexp (orig-fun regexp rep string &rest args) string)

(define-advice fussy-score (:around (orig-fun &rest args) allow-reordering)
  (prog2
      (advice-add 'replace-regexp-in-string :around 'my/allow-reordering-advice-replace-regexp)
      (apply orig-fun args)
    (advice-remove 'replace-regexp-in-string 'my/allow-reordering-advice-orderless-p)))
```

I understand that the word concatenation was a conscious choice and it is possible that other scorers do not support whitespace. In this case, maybe giving the user a choice per scorer would make sense?

**Comment by jojojames** [comment]
I'm guessing you're using orderless to filter and fzf to score&sort.

> (replace-regexp-in-string "\\\s" "" string) 

You could look into creating a list of scoring functions that would be able to accept a SPC and then conditionally skipping the replace-regexp by checking the value of fussy-score-fn.

PR accepted.

**Comment by kim366** [comment]
Thanks for your reply!

Another option I was thinking of, that would support all scorers would be to split all words by whitespace, score each word individually and then add/multiply the results.

I will implement such a custom scorer and use it for a while to see how well such an approach works. I‘ll get back to you then.

**Comment by kim366** [comment]
Hi again,

it's been a couple days and I've put a lot of thought into this problem. The big issue is that the scoring algorithms were not made with orderless in mind. Please keep in mind that I am fairly new to elisp so the code listings may not show good practices. They do work, however, and the concepts count.

## Solution 1
Inputting each word into the scoring algorithm individually and then adding or multiplying results.

If the scoring algorithm receives the raw query (could be set as a text property), this can be achieved from the user-side with a custom scoring algorithm, e.g.,
```elisp
(defun my/scoring-fn (str query &rest _args)
  (list (seq-reduce '*
		    (mapcar
		     (lambda (query-word)
		       (car (fussy-flx-rs-score str query-word)))
		     (split-string query))
		    1)))
(push 'my/scoring-fn fussy-score-fns-without-indices)
```

For each scoring algorithm the best reduction method would have to be found.

## Solution 2
Concatenating the query words in the order first seen by orderless.

Currently, fussy discards `org-goto` with the query `goto org` as the scoring algorithm receives `gotoorg`. Instead of concatenating the query in the given order, we could concatenate in the order first seen, in this case `orggoto`, which will match.

This is fairly close to the current implementation, only allowing the reordering of the query words, but no interleaving.

It is implemented here: https://github.com/kim366/fussy/commit/f2903e0d113b83628a9b79859178c483793e22ce

## Solution 3
Inputting not the user's query, but instead what orderless matched, into the scoring algorithm.

Example: matching the query `abc xyz` with `orderless-flex` against `ax_other_bycz` will highlight `[a][x]_other[b][y][c][z]`. We can concatenate the highlights as `axbycz` and feed them to the scoring algorithm.

This approach gives maximum compatibility with `orderless-flex` as no candidates will be filtered out due to incompatible scoring. It also allows us to fully configure orderless, using e.g., initialism for the first word and other matching styles for other words as detailed in the orderless docs. It will require some long-term real-world use to see how intuitive the sorting is.

This also means, though, that overlapping matches will be discarded: with orderless-flex, the query `org go` will match `org-info`, as the `g` in `go` overlaps with the `g` in `org` and is discarded. This seems to be intended orderless behavior. Most scoring algorithms rank consecutive matches higher. With this query, `org-goto` will not match as highly as it should, as orderless-flex is greedy but scoring algorithms might not be (hotfuzz, for example).

It is implemented here: https://github.com/kim366/fussy/commit/b4575139344df3dd3a282cafe0496b08e3dac5c3

## Conclusion
So solution 3 tries to maintain maximum compatiblity with orderless, being very "flex". Solution 2 tries to maintain maximum compatibility with the scoring algorithms, not allowing any interleaving.

I will use these for a while and see how I feel about them. What are your thoughts?

**Comment by jojojames** [comment]
First question is are you trying to make this work with all backends or just the fzf one? We can go from there.

**Comment by kim366** [comment]
Yes, all backends. I am currently using hotfuzz and it works wellAm 29/1/2024 um 09:40 schrieb James ***@***.***>:﻿
First question is are you trying to make this work with all backends or just the fzf one? We can go from there.

**Comment by jojojames** [comment]
Did you have thoughts after using your implementations after a while?

**Comment by jojojames** [comment]
I added something for this as a first step, e.g. exposing a variable that lets someone define which backends/scoring functions can take in whitespace. This should allow orderless to go to through to fussy at the basic level.

Since orderless uses a different syntax to fzf in terms of the extra whitspace handling/special character handling (e.g. ! ^ $ , etc etc), a next step could be to, before handing the final string to score to fzf, to do a string replace of characters on the orderless built string to what fzf can read and score.

orderless
```
! modifies the component with orderless-not. Both !bad and bad! will match strings that do not contain the pattern bad.
& modifies the component with orderless-annotation. The pattern will match against the candidate’s annotation (cheesy mnemonic: andnotation!).
, uses orderless-initialism.
= uses orderless-literal.
^ uses orderless-literal-prefix.
~ uses orderless-flex.
% makes the string match ignoring diacritics and similar inflections on characters (it uses the function char-fold-to-regexp to do this).
```

fzf native
```

sbtrkt | fuzzy-match | Items that match sbtrkt
-- | -- | --
'wild | exact-match (quoted) | Items that include wild
^music | prefix-exact-match | Items that start with music
.mp3$ | suffix-exact-match | Items that end with .mp3
!fire | inverse-exact-match | Items that do not include fire
!^music | inverse-prefix-exact-match | Items that do not start with music
!.mp3$ | inverse-suffix-exact-match | Items that do not end with .mp3

```

This doesn't seem too hard to do but I don't really use either feature that often for either so won't do it (seem reasonably easy to do though).

The other way to do it is to implement a new filter function that fzf can use afterwards. Something quick~

```
;; From `all-completions' documentation.
;; COLLECTION can also be a function to do the completion itself.
;; It receives three arguments: STRING, PREDICATE and t.
;; Whatever it returns becomes the value of `all-completions'.
;; If optional third argument PREDICATE is non-nil, it must be a function
;; of one or two arguments, and is used to test each possible completion.
;; A possible completion is accepted only if PREDICATE returns non-nil.
;;
;; The argument given to PREDICATE is either a string or a cons cell (whose
;; car is a string) from the alist, or a symbol from the obarray.
;; If COLLECTION is a hash-table, PREDICATE is called with two arguments:
;; the string key and the associated value.
(defun fussy-fzf-filter-predicate (string collection candidate
                                          &optional _hash-table-value)
  "Predicate for `all-completions' api.

STRING should be applied partially.
COLLECTION should be applied partially.
See `fussy-filter-fzf'.

CANDIDATE is the possible completion, either a string, a cons cell
(whos car is a string), or a symbol from the obarray.

If COLLECTION is a hash-table, candidate is the string key and
hash-table-value is the associated value."
  ;; e.g. (> (car (fzf-native-score "abc" "a" )) 0)
  (if-let* ((x (cond
                ((hash-table-p collection) candidate)
                ((stringp candidate) candidate)
                ((consp candidate) (car candidate))
                ((symbolp candidate) (symbol-name candidate))
                (:default 'skip)))
            (score (fzf-native-score x string (fussy--fzf-native-slab))))
      (progn
        ;; (message (format "c: %s s: %s score: %d" x string (car score)))
        (> (car score) 0))
    ;; Probably (functionp collection) == t
    ;; Don't bother checking as we can't do anything further.
    t))

(defun fussy-filter-fzf (string table pred point)
  "Match STRING to the entries in TABLE.

Use `fzf-native' for filtering."
  (let* ((beforepoint (substring string 0 point))
         (afterpoint (substring string point))
         (bounds (completion-boundaries beforepoint table pred afterpoint))
         (prefix (substring beforepoint 0 (car bounds)))
         (infix (concat
                 (substring beforepoint (car bounds))
                 (substring afterpoint 0 (cdr bounds))))
         ;; Seems infix is the right thing to score against...
         ;; (pred-prefix (apply-partially 'fussy-fzf-filter-predicate prefix table))
         (pred-infix (apply-partially 'fussy-fzf-filter-predicate infix table))
         (completion-regexp-list nil)
         ;; (_ (message (format "prefix: %s infix: %s" prefix infix)))
         (completions
          (all-completions prefix table pred-infix))
         (pattern
          (fussy-make-pcm-highlight-pattern beforepoint afterpoint bounds)))
    (list completions pattern prefix)))
```

Seems too slow for my taste, it might be faster writing it natively, but most of the calls are just to the native portions anyways. The filtering with an empty completion-regexp-list might be causing the most churn. If I have more time, I may see if I can optimize this more.

Re: splitting the input up and scoring separately, I don't think you want to do that, at the very least it's going to double the amount of scoring you need to do in addition to the fact that someone that does abc | ^def wants to OR their string together.

**Comment by kim366** [comment]
Hi, yes exposing more variables and functions is a good idea. I currently don‘t have time to work on this but I might continue some day

**Comment by jojojames** [comment]
<img width="1664" height="1884" alt="Image" src="https://github.com/user-attachments/assets/45a3cd91-163d-4374-be36-d8690b61463d" />

I added filtering by scoring (e.g. fzf backend filters & scores) in https://github.com/jojojames/fussy/pull/50

e.g. these rules:

```
sbtrkt | fuzzy-match | Items that match sbtrkt
-- | -- | --
'wild | exact-match (quoted) | Items that include wild
^music | prefix-exact-match | Items that start with music
.mp3$ | suffix-exact-match | Items that end with .mp3
!fire | inverse-exact-match | Items that do not include fire
!^music | inverse-prefix-exact-match | Items that do not start with music
!.mp3$ | inverse-suffix-exact-match | Items that do not end with .mp3
```

Can call (fussy-setup-fzf) or set 

these manually to see it:

  (setq fussy-filter-fn 'fussy-filter-by-scoring)
  (setq fussy-score-fn 'fussy-fzf-native-score)
  (setq fussy-score-ALL-fn 'fussy-fzf-score)

It won't be done for orderless because orderless is incompatible with scoring backends.

Can't guarantee it's stable though
